# Generated by Django 5.2 on 2026-09-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(choices=[("DSLR", "DSLR"), ("Projector", "Projector"), ("Mic", "Mic"), ("Tripod", "Tripod")], max_length=20)),
                ("deposit_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("daily_late_fee", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="EquipmentUnit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("asset_tag", models.CharField(max_length=100, unique=True)),
                ("status", models.CharField(choices=[("available", "Available"), ("booked", "Booked"), ("checked_out", "Checked Out"), ("maintenance", "Maintenance")], default="available", max_length=20)),
                ("equipment_type", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="units", to="inventory.equipmenttype")),
            ],
            options={"ordering": ["asset_tag"]},
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateField()),
                ("due_date", models.DateField()),
                ("returned_date", models.DateField(blank=True, null=True)),
                ("deposit_charged", models.DecimalField(decimal_places=2, max_digits=10)),
                ("late_fee_charged", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("status", models.CharField(choices=[("reserved", "Reserved"), ("checked_out", "Checked Out"), ("returned", "Returned"), ("cancelled", "Cancelled")], default="reserved", max_length=20)),
                ("borrower", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="bookings", to=settings.AUTH_USER_MODEL)),
                ("equipment_unit", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="bookings", to="inventory.equipmentunit")),
            ],
            options={"ordering": ["-start_date", "-id"]},
        ),
    ]
